-- Original query for DM parts inventory
-- This query retrieves inventory information for parts containing 'DM' in their part numbers

SELECT DISTINCT 
    TITLE.MAKE AS TITLE_MAKE,
    TITLE.PARTNO AS TITLE_PARTNO,
    TITLE.INACTIVE AS TITLE_INACTIVE,
    TITLE.DESCRIPTION AS TITLE_DESCRIPTION,
    TITLE.NSR AS TITLE_NSR,
    INVTORY.INVTYPE AS INVTORY_INVTYPE,
    INVTORY.SELLUOM AS INVTORY_SELLUOM,
    SUM(INVTORY.ONHANDQTY) AS INVTORY_QTY,
    COALESCE(sum(INVTORY.SHELFQTY),0) AS SHELFQTY,
    COALESCE(sum(INVTORY.SECONDARYSHELFQTY),0) AS SECONDARYSHELFQTY,
    COALESCE(sum(INVTORY.TERTIARYSHELFQTY),0) AS TERTIARYSHELFQTY,
    COALESCE(sum(INVTORY.FOURTHLYSHELFQTY),0) AS FOURTHLYSHELFQTY,
    COALESCE(sum((CASE WHEN INVTORY.SECONDARYSHELFDISABLED THEN INVTORY.SECONDARYSHELFQTY ELSE 0 END ) * COALESCE(INVTORY.EAQTY,1)), 0) AS SECONDARYSHELFDISABLEDQTY,
    COALESCE(sum((CASE WHEN INVTORY.TERTIARYSHELFDISABLED THEN INVTORY.TERTIARYSHELFQTY ELSE 0 END ) * COALESCE(INVTORY.EAQTY,1)), 0) AS TERTIARYSHELFDISABLEDQTY,
    COALESCE(sum((CASE WHEN INVTORY.FOURTHLYSHELFDISABLED THEN INVTORY.FOURTHLYSHELFQTY ELSE 0 END ) * COALESCE(INVTORY.EAQTY,1)), 0) AS FOURTHLYSHELFDISABLEDQTY,
    (case when INVTORY.selluom = INVQTY.selluom then INVQTY.ONHANDQTY 
          else (INVQTY.ONHANDQTY  /  coalesce((select ratio from titleconversion
                where make = TITLE.MAKE and partno = TITLE.PARTNO and selluom = INVTORY.SELLUOM and invqtyuom = invqty.selluom), 1))
     end ) as INVQTY_ONHANDQTY,
    (case when INVTORY.selluom = INVQTY.selluom then INVQTY.COMMITTEDQTY 
          else (INVQTY.COMMITTEDQTY  /  coalesce((select ratio from titleconversion
                where make = TITLE.MAKE and partno = TITLE.PARTNO and selluom = INVTORY.SELLUOM and invqtyuom = invqty.selluom), 1))
     end ) as INVQTY_COMMITTEDQTY,
    (case when INVTORY.selluom = INVQTY.selluom then INVQTY.BACKORDER 
          else (INVQTY.BACKORDER  /  coalesce((select ratio from titleconversion
                where make = TITLE.MAKE and partno = TITLE.PARTNO and selluom = INVTORY.SELLUOM and invqtyuom = invqty.selluom), 1))
     end ) as INVQTY_BACKORDER,
    INVQTY.SELLUOM AS INVQTY_SELLUOM,
    INVTORY.OFFICE AS OFFICE 
FROM INVTORY,
     TITLE,
     INVQTY
WHERE INVTORY.PARTNO LIKE '%DM%'
    AND INVTORY.MAKE = TITLE.MAKE
    AND INVTORY.PARTNO = TITLE.PARTNO
    AND INVTORY.MAKE = INVQTY.MAKE
    AND INVTORY.PARTNO = INVQTY.PARTNO
    AND INVTORY.OFFICE = INVQTY.OFFICE
    AND POSITION(INVTORY.SELLUOM IN COALESCE(TITLE.HIDEUOM, ''))<=0
GROUP BY 
    TITLE.MAKE,
    TITLE.PARTNO,
    TITLE.INACTIVE,
    TITLE.DESCRIPTION,
    TITLE.NSR,
    INVTORY.INVTYPE,
    INVTORY.SELLUOM,
    INVQTY.ONHANDQTY,
    INVQTY.COMMITTEDQTY,
    INVQTY.BACKORDER,
    INVQTY.SELLUOM,
    INVTORY.OFFICE
ORDER BY 
    TITLE_MAKE,
    TITLE_PARTNO,
    INVTORY_INVTYPE,
    INVTORY_QTY;
