# Database connection settings
database:
  host: localhost
  port: 5432
  dbname: test
  user: test
  password: test  # Consider using environment variables in production

# Query files to compare
original_query: examples/queries/original.sql
optimized_query: examples/queries/optimized.sql
