-- Drop tables if they exist
DROP TABLE IF EXISTS INVTORY;
DROP TABLE IF EXISTS INVQTY;
DROP TABLE IF EXISTS TITLECONVERSION;
DROP TABLE IF EXISTS TITLE;

-- Create TITLE table
CREATE TABLE TITLE (
    MAKE VARCHAR(50),
    PARTNO VARCHAR(50),
    INACTIVE BOOLEAN,
    DESCRIPTION TEXT,
    NSR BOOLEAN,
    HIDEUOM TEXT,
    PRIMARY KEY (MAKE, PARTNO)
);

-- Create INVTORY table
CREATE TABLE INVTORY (
    MAKE VARCHAR(50),
    PARTNO VARCHAR(50),
    OFFICE VARCHAR(50),
    INVTYPE VARCHAR(50),
    SELLUOM VARCHAR(10),
    ONHANDQTY INTEGER,
    SHELFQTY INTEGER,
    SECONDARYSHELFQTY INTEGER,
    TERTIARYSHELFQTY INTEGER,
    FOURTHLYSHELFQTY INTEGER,
    SECONDARYSHELFDISABLED BOOLEAN,
    TERTIARYSHELFDISABLED BOOLEAN,
    FOURTHLYSHELFDISABLED BOOLEAN,
    EAQTY INTEGER,
    FOREIGN KEY (MAKE, PARTNO) REFERENCES TITLE(MAKE, PARTNO)
);

-- Create INVQTY table
CREATE TABLE INVQTY (
    MAKE VARCHAR(50),
    PARTNO VARCHAR(50),
    OFFICE VARCHAR(50),
    SELLUOM VARCHAR(10),
    ONHANDQTY INTEGER,
    COMMITTEDQTY INTEGER,
    BACKORDER INTEGER,
    FOREIGN KEY (MAKE, PARTNO) REFERENCES TITLE(MAKE, PARTNO)
);

-- Create TITLECONVERSION table
CREATE TABLE TITLECONVERSION (
    MAKE VARCHAR(50),
    PARTNO VARCHAR(50),
    SELLUOM VARCHAR(10),
    INVQTYUOM VARCHAR(10),
    RATIO DECIMAL(10,2),
    FOREIGN KEY (MAKE, PARTNO) REFERENCES TITLE(MAKE, PARTNO)
);

-- Insert sample data
INSERT INTO TITLE (MAKE, PARTNO, INACTIVE, DESCRIPTION, NSR, HIDEUOM) VALUES
('ACME', 'DM123', false, 'Widget DM', false, NULL),
('ACME', 'DM456', false, 'Gadget DM', false, NULL),
('ACME', 'XY789', false, 'Non-DM Part', false, NULL);

INSERT INTO INVTORY VALUES
('ACME', 'DM123', 'MAIN', 'STOCK', 'EA', 100, 50, 20, 15, 15, false, false, false, 1),
('ACME', 'DM123', 'WAREHOUSE', 'STOCK', 'EA', 200, 100, 50, 30, 20, true, false, false, 1),
('ACME', 'DM456', 'MAIN', 'STOCK', 'EA', 150, 75, 40, 20, 15, false, true, false, 2),
('ACME', 'XY789', 'MAIN', 'STOCK', 'EA', 300, 150, 75, 50, 25, false, false, true, 1);

INSERT INTO INVQTY VALUES
('ACME', 'DM123', 'MAIN', 'EA', 100, 20, 5),
('ACME', 'DM123', 'WAREHOUSE', 'EA', 200, 40, 10),
('ACME', 'DM456', 'MAIN', 'EA', 150, 30, 8),
('ACME', 'XY789', 'MAIN', 'EA', 300, 60, 15);

INSERT INTO TITLECONVERSION VALUES
('ACME', 'DM123', 'EA', 'BOX', 10.00),
('ACME', 'DM456', 'EA', 'BOX', 20.00),
('ACME', 'XY789', 'EA', 'BOX', 50.00);
